# Generated by Django 5.2.3 on 2026-04-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_site_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='website',
            new_name='url',
        ),
    ]
