# Generated by Django 5.2.3 on 2026-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_pricehistory_composite_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pricehistory',
            name='ph_product_recorded_at_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
