# Generated by Django 5.2.3 on 2026-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_add_keywords_to_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
