"""
Django settings for price_comparison project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v*5tt3zm&3f0ky3&0saitr_bbo2%u&&20*5ietw=trxajmoufw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'django_celery_beat',

    'comparison',
    'product'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'price_comparison.urls'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", "http://56.228.24.214"
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'price_comparison.wsgi.application'
# ASGI_APPLICATION = 'price_comparison.asgi.application'

# Cache (django-redis) — reuses the existing Redis instance already running for Celery
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0"),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "pc",
    }
}

# Comparison token TTL in seconds (~5 min)
COMPARISON_TOKEN_TTL = 300

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'price_data'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'templates' / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "ryans_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "ryans.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "startech_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "startech.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "techland_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "techland.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "ucc_bd_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "ucc_bd.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "RyansScraper": {
            "handlers": ["ryans_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "StartechScraper": {
            "handlers": ["startech_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "TechlandScraper": {
            "handlers": ["techland_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "UccBdScraper": {
            "handlers": ["ucc_bd_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Celery
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

from kombu import Queue

CELERY_TASK_QUEUES = (
    Queue("ryans_queue"),
    Queue("startech_queue"),
    Queue("techland_queue"),
    Queue("ucc_bd_queue"),
)

CELERY_TASK_ROUTES = {
    "product.tasks.scrape_ryans": {"queue": "ryans_queue"},
    "product.tasks.scrape_startech": {"queue": "startech_queue"},
    "product.tasks.scrape_techland": {"queue": "techland_queue"},
    "product.tasks.scrape_ucc_bd": {"queue": "ucc_bd_queue"},
}

CELERY_BEAT_SCHEDULE = {
    "scrape-ryans": {
        "task": "product.tasks.scrape_ryans",
        "schedule": crontab(hour=0, minute=0),  # TODO: adjust time
        "options": {"queue": "ryans_queue"},
    },
    "scrape-startech": {
        "task": "product.tasks.scrape_startech",
        "schedule": crontab(hour=0, minute=0),  # TODO: adjust time
        "options": {"queue": "startech_queue"},
    },
    "scrape-techland": {
        "task": "product.tasks.scrape_techland",
        "schedule": crontab(hour=0, minute=0),  # TODO: adjust time
        "options": {"queue": "techland_queue"},
    },
    "scrape-ucc-bd": {
        "task": "product.tasks.scrape_ucc_bd",
        "schedule": crontab(hour=0, minute=0),  # TODO: adjust time
        "options": {"queue": "ucc_bd_queue"},
    },
}
